= 🍰 vaupie: Command line VAU client

= About

`🍰 vaupie` implements the https://github.com/gematik/api-erp/blob/master/docs/authentisieren.adoc#verschlüsselter-transportkanal-zur-vertrauenswürdigen-ausführungsumgebung-vau-transport[gematik VAU protocol] for ePrescription. It is designed to be used in combination with https://httpie.org[HTTPie] and https://github.com/gematik/ref-eRp-FD-Server[gematik reference implementation ePrescription Server]. 

`HTTPie` provides the `--offline` option which enables the following flow:
[square]
- `HTTPie` generates the HTTP-Reqiest and prints it to `stdout`
- `vaupie` reads the HTTP-Request from `stdin` 
- `vaupie` encrypts the HTTP-Request according to https://fachportal.gematik.de/fachportal-import/files/gemSpec_Krypt_V2.17.0.pdf[gemSpecKrypt], Kapitel 7.
- `vaupie` sends the encrypted request to server
- `vaupie` receives encrypted response from server and decrypts it
_ `vaupie` displays the plaintext response to `stdout`

.In Short:
[source,bash]
----
http --offline get vau/Task "`./vau.py auth`"|./vau.py req
----

= Usage

== Install and configure the server

Install https://www.rust-lang.org/learn/get-started[Rust]

.Clone repository from github
[source,bash]
----
git clone https://github.com/gematik/ref-eRp-FD-Server.git
cd ref-eRp-FD-Server
----


.Generate key pair and certificate usinf openssl 
[source,bash]
----
# generate key pair for VAU
openssl ecparam -name brainpoolP256r1 -genkey -out vau-key.pem
# IMPORTANT: use 'localhost' as Common Name, you can leave other fields empty
openssl req -new -x509 -key vau-key.pem -out vau-cert.pem -days 30
# display the VAU certificate
openssl x509 -in vau-cert.pem -text
----

.Start server 
[source,bash]
----
cargo run -p ref-erx-fd-server -- --vau-key vau-key.pem --vau-cert vau-cert.pem
----

.Test if server works
[source,bash]
----
# fetch VAU certificate from server and display it
http localhost:3000/VAUCertificate|openssl x509 -inform der -text
----

== Run `🍰 vaupie`

.Initialise Python virtualenv
[source,bash]
----
source venv.sh
----


.Initialise the VAU state
[source,bash]
----
# ./vau.py init <VAU ENDPOINT> <JWT AUTH TOKEN>
# WARNING: due to a bug the server will not work if you provide the real JWT. the Token must be any HEX value.
./vau.py init http://localhost:3000/ AAAA0000
----

.Get all Tasks
[source,bash]
----
http --offline get vau/Task "`./vau.py auth`"|./vau.py req
----

----
HTTP/1.1 200 OK
content-length: 71
connection: close
content-type: application/fhir+xml
date: Sun, 20 Sep 2020 15:41:52 GMT

<Bundle xmlns="http://hl7.org/fhir"><type value="collection"/></Bundle>
----
